#pragma once

#define FILTER_ORDER 1 // 1, ..., N; FILTER_ORDER = 2 * FILTER_ORDER + 1, [FILTER_ORDERxFILTER_ORDER]

#define CONVFILTER2
//#define CONVFILTER1

#define SIGMA 0.5

//SELECT ONLY ONE TYPE OF FILTER:
//#define MEDIAN_KERNEL
#define GAUSIAN_KERNEL
//#define PREWITT_HORIZONTAL_KERNEL
//#define PREWITT_VERTICAL_KERNEL
//#define SOBEL_HORIZONTAL_KERNEL
//#define SOBEL_VERTICAL_KERNEL